### ISSUE TITLE
The `indexOf()` method of `Array` does not work correctly under .NET 9

### ISSUE THREAD

**Issue by Taritsyn** [yantrajs/yantra#100]
Hello, Akash!

After switching to .NET 9, behavior of the `indexOf()` method of `Array` changed. To reproduce this error, I created a example:

```csharp
using System;

using YantraJS.Core;

namespace TestYantra
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var context = new JSContext())
            {
                context.Execute("var arr = [2, 5, 9, 2]");
                int result = context.Eval("arr.indexOf(2, -1);").AsInt32OrDefault();

                Console.WriteLine("Result: {0}", result);
            }
        }
    }
}
```

Under normal conditions, result of this example should be `3`, but under .NET 9 we get `0`.

**Comment by ackava** [comment]
@Taritsyn Thanks for reporting this, I think I found a breaking change in .NET 9, https://learn.microsoft.com/en-us/dotnet/core/compatibility/jit/9.0/fp-to-integer , this could be the root issue and I will try to find a fix and update the library soon.

**Comment by Taritsyn** [comment]
Thank you very much!
