### ISSUE TITLE
The `ClrType.From` method does not work with the `System.Guid` type under .NET 9

### ISSUE THREAD

**Issue by Taritsyn** [yantrajs/yantra#101]
Hello, Akash!

After switching to .NET 9, in the `ClrType.From` method when working with the `System.Guid` type an error “Cannot bind to the target method because its signature is not compatible with that of the delegate type.” began to occur. To reproduce this error, I created a example:

```csharp
using System;

using YantraJS.Core;
using YantraJS.Core.Clr;

namespace TestYantra
{
    internal class Program
    {
        static void Main(string[] args)
        {
            using (var context = new JSContext())
            {
                JSValue guidTypeValue = ClrType.From(typeof(Guid));
                context["guid"] = guidTypeValue;
                string result = context.Eval("guid.empty.toString()").ToString();

                Console.WriteLine("Result: {0}", result);
            }
        }
    }
}
```

Under normal conditions, result of this example should be `00000000-0000-0000-0000-000000000000`.

**Comment by ackava** [comment]
@Taritsyn Thanks for reporting this, I will look and update soon.

**Comment by ackava** [comment]
@Taritsyn This will take little time, I upgraded unit test set to .NET 9 and almost 10% of unit tests are failing due to change in bitwise operations on casting. And due to one more breaking change, field access on .NET type is also failing, I will fix these issues over coming weekend.
