### ISSUE TITLE
Importing CLR Module Throws Null Reference Exception

### ISSUE THREAD

**Issue by NorthernLight1** [yantrajs/yantra#39]
I was trying to figure out how to import and use the clr module within JavaScript but I am getting an null reference exception. 

```
                var context = new JSModuleContext();
                var r = context.Eval("import clr from \"clr\"");
```

**Comment by NorthernLight1** [comment]
I was able to get it working with RunAsync(),  I was using Eval() to test some stuff without putting it in a script file.

**Comment by NorthernLight1** [comment]
Is it possible to create a better overload for JSModuleContext.RegisterModule so that I can pass the name of the module and the type?

`
 var context = new JSModuleContext();
context.RegisterModule("CustomClass", typeof(CustomClass))
`

**Comment by ackava** [comment]
`var context = new JSModuleContext(); context.RegisterModule("CustomClass", typeof(CustomClass).Marshal());`

This should work.
