### ISSUE TITLE
Ability to disable a Camel case at the engine level

### ISSUE THREAD

**Issue by Taritsyn** [yantrajs/yantra#66]
Hello, Akash!

Most JS engines, when embedding .NET types and objects, uses a Pascal case to access its members. I know that this behavior can be changed using an `JSExportSameName` attribute, but this is not always convenient. It would be convenient to disable a Camel case when creating an instance of the `JSContext` class.

**Comment by ackava** [comment]
@Taritsyn Yes I can definitely do it, I will keep this issue open till a fix is released and I will update you.

**Comment by Taritsyn** [comment]
Thanks for quick response!

**Comment by ackava** [comment]
@Taritsyn New release addresses the issue https://github.com/yantrajs/yantra/releases/tag/v1.2.109

**Comment by Taritsyn** [comment]
Thank you very much!
