### ISSUE TITLE
Bug: Template literals

### ISSUE THREAD

**Issue by animehunter** [yantrajs/yantra#80]
I found a bug with template literals.

``` `${1 + 1}` ``` outputs 1 instead of 2
Similarly, ```var a = 1; var b = 1; `${a + b}` ``` also outputs 1 instead of 2

**Comment by ackava** [comment]
@animehunter Bug has been fixed in new release, please star the repo if you like YantraJS.

**Comment by animehunter** [comment]
Done
Thank you
