### ISSUE TITLE
unexpected console output while using JSModuleContext

### ISSUE THREAD

**Issue by fsz1987** [yantrajs/yantra#97]
js host code:
```cs
        var engine = new JsModuleContext();
        engine.ConsoleEvent += Engine_ConsoleEvent;
        engine.Log += Engine_Log;


        await engine.RunAsync(rootdir,"test.js");
```
test.js
```js
//test.js
console.log ("hello");
```

after compile and test this program I got unexpected console output:
```
2024/4/9 7:11:24 - Compiling module V:\test\yantratest\yantratest\js\./test.js
hello
```
which is problematic , cause it may break my console output format.
I checked YantraJs source found the problem is in JSModuleContext.js line 380

```cs
Console.WriteLine($"{DateTime.Now} - Compiling module {module.filePath}");
```

is this part of design ?

**Comment by ackava** [comment]
@fsz1987 no it is not part of design, I will remove it. It was added for debugging.
